### PR TITLE
patchAll method

### PR DESCRIPTION
**Pull request by manubb**
Hello
Similary to deleteAll patch, i suggest to add a patchAll method and that patchAll and deleteAll should return number of affected rows. Can you review and possibly merge this?

### CODE REVIEW

**Comment by koskimas** [comment]
This is a good addition. Tests for these methods would be nice also. 

For some reason the tests fail on mysql event though no tests were added. That probably has nothing to do with this pull request. I'll have to check out what is going on there.

**Comment by manubb** [comment]
Ok. I'll have a look at adding tests later today.

**Comment by manubb** [comment]
Here are the tests. I ran them with sqlite3 and postgresql (not with mysql). 
Hope you could merge and publish this.

**Comment by koskimas** [comment]
Thanks!

**Pull request merged**
