### PR TITLE
Add a DELETE method for collections.

### PR DESCRIPTION
**Pull request by manubb**
I suggest to add a DELETE for collections that allows multiple delete. For example:
DELETE /persons removes all Persons.
DELETE /persons?firstName=Jennifer removes all Persons whose firstName is 'Jennifer'.
Could you please review and possibly merge the attached commit?
Manuel

### CODE REVIEW

**Comment by kapouer** [comment]
@koskimas is there something we can do to help merging this PR ?

**Comment by koskimas** [comment]
I'm sorry for the radio silence, but I currently have very little time for this project. I will continue it at some point and it is by no means forgotten. I'm surprised someone is using this without any documentation :D. I'll try to find time to review this during next week.

**Comment by kapouer** [comment]
No problem, thanks !

**Comment by kapouer** [comment]
Oh and yes, objection-rest just rocks !

**Pull request merged**
