### PR TITLE
routeFormat

### PR DESCRIPTION
**Pull request by rawgroundbeef**
Hey there! Thanks for making this library. It's going to save us a lot of time.

The pluralizing and camelCasing for route names didn't work for us. Instead, we've implemented a function to the api called `routeFormat`.

I wanted to shoot a pull request over to you to see if you might want to add this into your project.

Cheers!

### CODE REVIEW

**Comment by kapouer** [comment]
Why not, but default `routeFormat` should really reproduce old behavior if we don't want to break api.

**Comment by rawgroundbeef** [comment]
good point. old tests work without changes.

thanks!!

**Comment by rawgroundbeef** [comment]
just realizing that pluralize was a public function, just not documented in the api.

should I keep that in there?

**Comment by kapouer** [comment]
i think even the last time i used objection-rest i called that function myself.

**Comment by rawgroundbeef** [comment]
Hey man, turns out we're going another direction. Do you want to keep this code? Otherwise I'll probably delete my fork this week.

@kapouer

**Pull request closed without merging**
